baseurl = "/"
languageCode = "zh-cmn-Hant"
title = "Bingo"
theme = "hugo-bingo"

disableHugoGeneratorInject = true
enableEmoji = true
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
footnoteReturnLinkContents = "↩"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/"
    weight = 10

  [[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/"
    weight = 20
